### PR TITLE
fix double lockfile, test integration

### PR DESCRIPTION
**Pull request by daimeng**
testing if PR creator has is causing the integration issue

### CODE REVIEW

**Comment by daimeng** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>b537319</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://zodiac-landing-3eusbgjya-daimeng.vercel.app'>https://zodiac-landing-3eusbgjya-daimeng.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/daimeng/zodiac-landing/Li54EjN5MJ9tdZSA1iYEFeUNjmrp'>https://vercel.com/daimeng/zodiac-landing/Li54EjN5MJ9tdZSA1iYEFeUNjmrp</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/daimeng/zodiac-landing/actions/runs/2660308401)

**Comment by daimeng** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>463cd96</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://zodiac-landing-1i4vttwtu-daimeng.vercel.app'>https://zodiac-landing-1i4vttwtu-daimeng.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/daimeng/zodiac-landing/9aAaRwtzQWcStN2adnUK9WYQhTPj'>https://vercel.com/daimeng/zodiac-landing/9aAaRwtzQWcStN2adnUK9WYQhTPj</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/daimeng/zodiac-landing/actions/runs/2660604566)

**Comment by daimeng** [comment]
Seeing if the vercel stuff still works without lockfile

**Comment by kimchicoffee** [comment]
cool!

**Pull request merged**
